import { City, Track } from '@/app/types/match';

export const CITIES: City[] = [
    { id: 'edinburgh', name: 'Edinburgh', x: 14.90, y: 4.19 },
    { id: 'london', name: 'London', x: 20.86, y: 27.35 },
    { id: 'paris', name: 'Paris', x: 25.69, y: 41.16 },
    { id: 'bruxelles', name: 'Bruxelles', x: 29.58, y: 30.77 },
    { id: 'amsterdam', name: 'Amsterdam', x: 30.65, y: 22.87 },
    { id: 'frankfurt', name: 'Frankfurt', x: 38.00, y: 34.63 },
    { id: 'munchen', name: 'Munchen', x: 43.65, y: 44.92 },
    { id: 'zurich', name: 'Zurich', x: 37.73, y: 48.87 },
    { id: 'marseille', name: 'Marseille', x: 31.56, y: 70.13 },
    { id: 'roma', name: 'Roma', x: 45.43, y: 77.39 },
    { id: 'venezia', name: 'Venezia', x: 45.07, y: 58.96 },
    { id: 'wien', name: 'Wien', x: 52.97, y: 44.54 },
    { id: 'budapest', name: 'Budapest', x: 58.16, y: 48.24 },
    { id: 'warszawa', name: 'Warszawa', x: 62.00, y: 23.59 },
    { id: 'danzig', name: 'Danzig', x: 57.39, y: 12.53 },
    { id: 'riga', name: 'Riga', x: 68.02, y: -1.00 },
    { id: 'wilno', name: 'Wilno', x: 70.30, y: 10.78 },
    { id: 'petrograd', name: 'Petrograd', x: 80.14, y: -16.55 },
    { id: 'moskva', name: 'Moskva', x: 94.31, y: 5.22 },
    { id: 'smolensk', name: 'Smolensk', x: 83.46, y: 10.29 },
    { id: 'kyiv', name: 'Kyiv', x: 80.51, y: 32.86 },
    { id: 'kharkov', name: 'Kharkov', x: 91.61, y: 35.24 },
    { id: 'rostov', name: 'Rostov', x: 98.37, y: 49.61 },
    { id: 'sevastopol', name: 'Sevastopol', x: 86.35, y: 63.25 },
    { id: 'sochi', name: 'Sochi', x: 98.43, y: 68.53 },
    { id: 'istanbul', name: 'Istanbul', x: 77.50, y: 82.05 },
    { id: 'angora', name: 'Angora', x: 85.05, y: 87.65 },
    { id: 'erzurum', name: 'Erzurum', x: 101.42, y: 87.80 },
    { id: 'madrid', name: 'Madrid', x: 13.90, y: 85.13 },
    { id: 'lisboa', name: 'Lisboa', x: 3.32, y: 93.96 },
    { id: 'cadiz', name: 'Cadiz', x: 8.87, y: 105.40 },
    { id: 'barcelona', name: 'Barcelona', x: 25.34, y: 80.09 },
    { id: 'pamplona', name: 'Pamplona', x: 17.91, y: 72.65 },
    { id: 'brest', name: 'Brest', x: 12.38, y: 43.59 },
    { id: 'dieppe', name: 'Dieppe', x: 23.21, y: 35.60 },
    { id: 'essen', name: 'Essen', x: 34.75, y: 27.62 },
    { id: 'kobenhavn', name: 'Kobenhavn', x: 45.57, y: 5.63 },
    { id: 'stockholm', name: 'Stockholm', x: 56.27, y: -13.40 },
    { id: 'berlin', name: 'Berlin', x: 47.19, y: 22.07 },
    { id: 'palermo', name: 'Palermo', x: 47.11, y: 97.12 },
    { id: 'brindisi', name: 'Brindisi', x: 56.02, y: 84.01 },
    { id: 'athena', name: 'Athena', x: 67.28, y: 97.81 },
    { id: 'sofia', name: 'Sofia', x: 66.49, y: 73.25 },
    { id: 'bucuresti', name: 'Bucuresti', x: 71.90, y: 64.24 },
    { id: 'sarajevo', name: 'Sarajevo', x: 56.94, y: 67.21 },
    { id: 'zagrab', name: 'Zagrab', x: 52.21, y: 57.01 },
    { id: 'milano', name: 'Milano', x: 38.99, y: 58.83 },
];

export const TRACKS: Track[] = [
    { id: 'edi-lon-1', city1: 'edinburgh', city2: 'london', length: 4, double: true },
    { id: 'edi-lon-2', city1: 'edinburgh', city2: 'london', length: 4, double: true },
    { id: 'lon-die-1', city1: 'london', city2: 'dieppe', length: 2, double: true },
    { id: 'lon-die-2', city1: 'london', city2: 'dieppe', length: 2, double: true },
    { id: 'lon-ams-1', city1: 'london', city2: 'amsterdam', length: 2, double: false },
    { id: 'die-bre-1', city1: 'dieppe', city2: 'brest', length: 2, double: false },
    { id: 'die-par-1', city1: 'dieppe', city2: 'paris', length: 1, double: false },
    { id: 'bre-par-1', city1: 'brest', city2: 'paris', length: 3, double: false },
    { id: 'bre-pam-1', city1: 'brest', city2: 'pamplona', length: 4, double: false },
    { id: 'pam-par-1', city1: 'pamplona', city2: 'paris', length: 4, double: true },
    { id: 'pam-par-2', city1: 'pamplona', city2: 'paris', length: 4, double: true },
    { id: 'pam-mad-1', city1: 'pamplona', city2: 'madrid', length: 3, double: true },
    { id: 'pam-mad-2', city1: 'pamplona', city2: 'madrid', length: 3, double: true },
    { id: 'pam-bar-1', city1: 'pamplona', city2: 'barcelona', length: 2, double: false },
    { id: 'mad-lis-1', city1: 'madrid', city2: 'lisboa', length: 3, double: false },
    { id: 'mad-cad-1', city1: 'madrid', city2: 'cadiz', length: 3, double: false },
    { id: 'mad-bar-1', city1: 'madrid', city2: 'barcelona', length: 2, double: false },
    { id: 'lis-cad-1', city1: 'lisboa', city2: 'cadiz', length: 2, double: false },
    { id: 'par-bru-1', city1: 'paris', city2: 'bruxelles', length: 2, double: true },
    { id: 'par-bru-2', city1: 'paris', city2: 'bruxelles', length: 2, double: true },
    { id: 'par-fra-1', city1: 'paris', city2: 'frankfurt', length: 3, double: true },
    { id: 'par-fra-2', city1: 'paris', city2: 'frankfurt', length: 3, double: true },
    { id: 'par-zur-1', city1: 'paris', city2: 'zurich', length: 3, double: false },
    { id: 'par-mar-1', city1: 'paris', city2: 'marseille', length: 4, double: false },
    { id: 'bar-mar-1', city1: 'barcelona', city2: 'marseille', length: 4, double: false },
    { id: 'mar-zur-1', city1: 'marseille', city2: 'zurich', length: 2, double: false },
    { id: 'mar-rom-1', city1: 'marseille', city2: 'roma', length: 4, double: false },
    { id: 'bru-ams-1', city1: 'bruxelles', city2: 'amsterdam', length: 1, double: false },
    { id: 'bru-fra-1', city1: 'bruxelles', city2: 'frankfurt', length: 2, double: false },
    { id: 'ams-ess-1', city1: 'amsterdam', city2: 'essen', length: 3, double: false },
    { id: 'ams-fra-1', city1: 'amsterdam', city2: 'frankfurt', length: 2, double: false },
    { id: 'ess-kob-1', city1: 'essen', city2: 'kobenhavn', length: 3, double: true },
    { id: 'ess-kob-2', city1: 'essen', city2: 'kobenhavn', length: 3, double: true },
    { id: 'ess-ber-1', city1: 'essen', city2: 'berlin', length: 2, double: false },
    { id: 'fra-ber-1', city1: 'frankfurt', city2: 'berlin', length: 3, double: true },
    { id: 'fra-ber-2', city1: 'frankfurt', city2: 'berlin', length: 3, double: true },
    { id: 'fra-mun-1', city1: 'frankfurt', city2: 'munchen', length: 2, double: false },
    { id: 'mun-zur-1', city1: 'munchen', city2: 'zurich', length: 2, double: false },
    { id: 'zur-ven-1', city1: 'zurich', city2: 'venezia', length: 2, double: false },
    { id: 'zur-mil-1', city1: 'zurich', city2: 'milano', length: 2, double: false },
    { id: 'mar-mil-1', city1: 'marseille', city2: 'milano', length: 3, double: false }
];

export const TICKETS = [
    { id: 'ath-ang', city1: 'athena', city2: 'angora', points: 5 },
    { id: 'bud-sof', city1: 'budapest', city2: 'sofia', points: 5 },
    { id: 'fra-kob', city1: 'frankfurt', city2: 'kobenhavn', points: 5 },
    { id: 'ros-erz', city1: 'rostov', city2: 'erzurum', points: 5 },
    { id: 'sof-smy', city1: 'sofia', city2: 'smyrna', points: 5 }, // smyrna is not in CITIES, replacing with izmir/istanbul logic? check CITIES
    // Checking CITIES: 'istanbul'. Let's use 'istanbul'.
    { id: 'kyi-pet', city1: 'kyiv', city2: 'petrograd', points: 6 },
    { id: 'zur-bud', city1: 'zurich', city2: 'budapest', points: 6 },
    { id: 'war-smo', city1: 'warszawa', city2: 'smolensk', points: 6 },
    { id: 'zag-bre', city1: 'zagrab', city2: 'brest', points: 7 },
    { id: 'par-edi', city1: 'paris', city2: 'edinburgh', points: 7 },
    { id: 'lon-ber', city1: 'london', city2: 'berlin', points: 7 },
    { id: 'edi-par', city1: 'edinburgh', city2: 'paris', points: 7 },
    { id: 'ams-pam', city1: 'amsterdam', city2: 'pamplona', points: 7 },
    { id: 'rom-smy', city1: 'roma', city2: 'smyrna', points: 8 }, // Use istanbul?
    { id: 'pal-con', city1: 'palermo', city2: 'istanbul', points: 8 },
    { id: 'sar-sev', city1: 'sarajevo', city2: 'sevastopol', points: 8 },
    { id: 'mad-zur', city1: 'madrid', city2: 'zurich', points: 8 },
    { id: 'ber-mos', city1: 'berlin', city2: 'moskva', points: 12 },
    { id: 'par-wie', city1: 'paris', city2: 'wien', points: 12 }, // Use Wien
    { id: 'edi-ath', city1: 'edinburgh', city2: 'athena', points: 21 },
    { id: 'cad-sto', city1: 'cadiz', city2: 'stockholm', points: 21 },
    { id: 'bre-pet', city1: 'brest', city2: 'petrograd', points: 20 },
    { id: 'lis-dan', city1: 'lisboa', city2: 'danzig', points: 20 }
];
